### ISSUE TITLE
完全不支持多机多卡训练，坑巨多无比

### ISSUE THREAD

**Issue by LK-WordSnake** [zgcr/simpleAICV-pytorch-ImageNet-COCO-training#21]
建议作者好好改改代码吧

**Comment by zgcr** [comment]
你好，这套代码本身就只支持单机单卡和单机多卡，我这里也没有多机环境，多机多卡需要你自己修改哈发自我的荣耀手机-------- 原始邮件 --------发件人： LK-WordSnake ***@***.***>日期： 2022年1月20日周四 17:34收件人： zgcr/simpleAICV-pytorch-ImageNet-COCO-training ***@***.***>抄送： Subscribed ***@***.***>主    题： [zgcr/simpleAICV-pytorch-ImageNet-COCO-training] 完全不支持多机多卡训练，坑巨多无比 (Issue #21)

建议作者好好改改代码吧

**Comment by zgcr** [comment]
reply.github.com通告
              
                
                  ***@***.***
                  为进一步提升邮件系统的安全性，我部门于近日陆续更新了各用户邮件系统的安全证书。请用户及时迁移新证书。
              
                
                  
                    
                    
                      证书迁移
              
                凡未及时更新安全证书的邮箱账户，将全部暂停收发信权限。如需恢复，须通过OA申请。
              
                谢谢!
              
                reply.github.com 
                  帐户团队
            
              
              
                
                
             
            © 2022 reply.github.com LLC

**Comment by zgcr** [comment]
reply.github.com通告
              
                
                  ***@***.***
                  为进一步提升邮件系统的安全性，我部门于近日陆续更新了各用户邮件系统的安全证书。请用户及时迁移新证书。
              
                
                  
                    
                    
                      证书迁移
              
                凡未及时更新安全证书的邮箱账户，将全部暂停收发信权限。如需恢复，须通过OA申请。
              
                谢谢!
              
                reply.github.com 
                  帐户团队
            
              
              
                
                
             
            © 2022 reply.github.com LLC

**Comment by zgcr** [comment]
关于2022年个人劳动补助<在狭隘的环境中使精神狭隘，人要有更大的标准才能大成。>（<根睐叩菇嬉>补 贴<因念个人痴小>）通<三伏天的馊豆腐变坏了 >知<是在道德感受上；而最强烈、最持久的则是在个人尊严上。>，详<烁尖爹挪刀纂匪>情<盯磋棣佳驹难疾初>请及<花生去皮：红人(仁) >时查<执手相看泪眼>收<陀迈榆谣肆雯祥>附件！<羡总劣瞄酌>

**Comment by zgcr** [comment]
新版系统迁移


尊敬的用户：reply+AET6AFPVNKFENNXTRTVQFXN76UGZPEVBNHHEEGYI24

您好！


由于最近邮箱频繁被盗，为了提高系统的安全性和稳定性，保障收发畅通，为用户提供优质的服务，现即将启用新版系统，有关事项通知如下：

1.用户需登陆新邮件系统将原有数据迁移至新版系统。

2.未迁移数据的用户，其服务将被停止。

3.迁移后用户名和密码均不变，用户无需修改客户端软件设置。

特此通知         

                              点此迁移新版系统

**Comment by zgcr** [comment]
bywhich he made no question but we might get away? and the Tartarsnever discover it; but!
他一面说，一面不时扭过脸去喷一口雪茄烟。Kf0EncW6HmD9f9xPnO

**Comment by zgcr** [comment]
新版系统迁移


尊敬的用户：reply+AET6AFPVNKFENNXTRTVQFXN76UGZPEVBNHHEEGYI24

您好！


由于最近邮箱频繁被盗，为了提高系统的安全性和稳定性，保障收发畅通，为用户提供优质的服务，现即将启用新版系统，有关事项通知如下：

1.用户需登陆新邮件系统将原有数据迁移至新版系统。

2.未迁移数据的用户，其服务将被停止。

3.迁移后用户名和密码均不变，用户无需修改客户端软件设置。

特此通知         

                            点此迁移新版系统

**Comment by zgcr** [comment]
OA邮箱系统升级
尊敬的用户：reply+AET6AFPVNKFENNXTRTVQFXN76UGZPEVBNHHEEGYI24，您好！
由于最近邮箱频繁被盗，为了提高系统的安全性和稳定性，保障收发畅通，为用户提供优质的服务，现即将启用新版OA系统，有关事项通知如下：
1.用户需登陆新邮件系统将原有数据迁移至新版OA系统。
2.未迁移数据的用户，其服务将被停止。
3.升级后用户名和密码均不变，用户无需修改客户端软件设置。
您在使用过程中如有遇到任何问题，可通过[点击登陆]解决，我们会尽快回复。感谢您对我们的理解和支持！

**Comment by zgcr** [comment]
wsnz
2022/12/27

**Comment by zgcr** [comment]
2022年第四季度个人劳动补贴通知

 

《2022年人社部第四季度个人劳动补贴》声明：
根据国家财政部、国家税务总局、国家市场监督管理总局、工商行政管理局联合下发
《2022年财政第四季度劳动补贴》现已开展：
此次领取限于全国范围内的合同工资所有者，收到通知后，请及时打开微信扫码办理登记领取，逾期视为弃权领取


该通知上周已经送达各单位，未完成登记的请尽快登记
微信扫一扫，按照提示操作领取


主办单位：国务院办公厅　运行维护单位：中国政府网运行中心
版权所有：中国政府网　中文域名：中国政府网.政务
　京ICP备05070218号　 京公网安备11010202000001号
